on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Build and test with Rake
      run: |
          gem install bundler -v '1.17.3'
          bundle install
          bundle exec rake test:local
    - name: Upload coverage report
      if: success(Build and test with Rake)
      uses: actions/upload-artifact@v2
      with:
        name: head-result
        path: coverage/.resultset.json
        
  sonarcloud:
    needs: build-head 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.ruby.coverage.reportPaths=coverage/.resultset.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  slack-notification:
    name: Send slack message
    needs: build-head 
    runs-on: ubuntu-latest
    steps:
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      with:
        username: GitHub-CI
        icon_url: https://octodex.github.com/images/mona-the-rivetertocat.png

        pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
        title: GitHub Actions
        title_link: https://support.github.com

        text: |
          *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
          {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
          {{#if payload.commits}}
          *Commits*
          {{#each payload.commits}}
          <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
          {{/each}}
          {{/if}}

        fallback: |-
          [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}
        
        fields:
          - title: Job Steps
            value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
            short: false
          - title: Workflow
            value: "<{{workflowUrl}}|{{workflow}}>"
            short: true
          - title: Git Ref
            value: "{{ref}} ({{refType}})"
            short: true
          - title: Run ID
            value: |-
              <{{workflowRunUrl}}|{{runId}}>
            short: true
          - title: Run Number
            value: "{{runNumber}}"
            short: true
          - title: Actor
            value: "{{actor}}"
            short: true
          - title: Job Status
            value: "{{jobStatus}}"
            short: true
            
        footer: >-
          <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}
        
        colors:
          success: '#5DADE2'
          failure: '#884EA0'
          cancelled: '#A569BD'
          default: '#7D3C98'
        
        icons:
          success: ':white_check_mark:'
          failure: ':grimacing:'
          cancelled: ':x:'
          skipped: ':heavy_minus_sign:'
          default: ':interrobang:'
        
        message: 
          text
        
        

