on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
    - name: Build and test with Rake
      run: |
          gem install bundler -v '1.17.3'
          bundle install
          bundle exec rake test:local
    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage/.resultset.json
    - name: see current carpet
      run: |
          cd coverage
          ls -a 
   
  sonarcloud:
    needs: build-head 
    runs-on: ubuntu-latest
    steps:
    - name: downdload code-coverage artifact  
      uses: actions/download-artifact@v2
      with:
        name: code-coverage
    - name: move report tu results carpet
      run: |
          ls -s
          mkdir results
          mv .resultset.json ./results/
          ls -a
          cd results
          ls -a

    - name: send slack message
      run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#qa-process\", \"username\": \"webhookbot\", \"text\": \"Build complete...\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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

    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.ruby.coverage.reportPaths=.results/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}




  





