on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: act10ns/slack@v1.5.0
      with:
      status: starting
          channel: '#qa-process'
          message: Starting Build...
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Build and test with Rake
      run: |
          gem install bundler -v '1.17.3'
          bundle install
          bundle exec rake test:local
    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: head-result
        path: coverage/.resultset.json
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        
  sonarcloud:
    needs: build-head 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.ruby.coverage.reportPaths=coverage/.resultset.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}


  





